const CATEGORIES_PANEL = 'CATEGORIES_PANEL';
export const SET_CATEGORIES = `${CATEGORIES_PANEL}_SET_CATEGORIES`;
export const SET_IS_LOADING_CATEGORIES = `${CATEGORIES_PANEL}_IS_LOADING_CATEGORIES`;
export const SET_NEW_CATEGORY = `${CATEGORIES_PANEL}_SET_NEW_CATEGORY`;
