const TASKS_PANEL = 'TASKS_PANEL';
export const SET_TASKS = `${TASKS_PANEL}_SET_TASKS`;
export const SET_IS_LOADING = `${TASKS_PANEL}_IS_LOADING`;
export const SET_NEW_TASK = `${TASKS_PANEL}_NEW_TASK`;
