const TASKS_PANEL = 'TASKS_PANEL';
export const SET_TASKS = `${TASKS_PANEL}_SET_TASKS`;
export const SET_IS_LOADING_TASKS = `${TASKS_PANEL}_IS_LOADING_TASKS`;
export const SET_NEW_TASK = `${TASKS_PANEL}_NEW_TASK`;
export const SET_FILTER_TEXT = `${TASKS_PANEL}_SET_FILTER_TEXT`;
export const SET_FILTER_DONE = `${TASKS_PANEL}_SET_FILTER_DONE`;
